version: "3.8"

services:

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - webapi
    depends_on:
      - rabbitmq
    command: sh -c "alembic upgrade head && python3 main.py"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ru_manga
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - webapi
    ports:
      - "5433:5433"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

networks:
  default:
    external:
      name: webapi